import type { Utterance } from "./translation-types";

export const DEMO_UTTERANCES: Utterance[] = [
  {
    id: "demo-1",
    sequence: 1,
    at: "00:03",
    sourceLanguage: "ja",
    ja: "こんちわ、今日は暑いですね",
    en: "Hello, it is hot today",
  },
  {
    id: "demo-2",
    sequence: 2,
    at: "00:08",
    sourceLanguage: "en",
    ja: "ええ、とてもあつね",
    en: "YES, too hot!",
  },
  {
    id: "demo-3",
    sequence: 3,
    at: "00:12",
    sourceLanguage: "ja",
    ja: "元気ですか？",
    en: "How are you?",
  },
  {
    id: "demo-4",
    sequence: 4,
    at: "00:16",
    sourceLanguage: "en",
    ja: "はい、元気です！",
    en: "Yep, I'm fine",
  },
  {
    id: "demo-5",
    sequence: 5,
    at: "00:22",
    sourceLanguage: "ja",
    ja: "週末は何をする予定ですか？",
    en: "What are you planning to do this weekend?",
  },
  {
    id: "demo-6",
    sequence: 6,
    at: "00:28",
    sourceLanguage: "en",
    ja: "友達と海に行くつもりです。",
    en: "I'm going to the beach with some friends.",
  },
  {
    id: "demo-7",
    sequence: 7,
    at: "00:34",
    sourceLanguage: "ja",
    ja: "いいですね。どこの海ですか？",
    en: "That sounds nice. Which beach are you going to?",
  },
  {
    id: "demo-8",
    sequence: 8,
    at: "00:41",
    sourceLanguage: "en",
    ja: "まだ決めていません。天気次第ですね。",
    en: "We haven't decided yet. It depends on the weather.",
  },
  {
    id: "demo-9",
    sequence: 9,
    at: "00:49",
    sourceLanguage: "ja",
    ja: "予報では土曜日は晴れるそうです。",
    en: "The forecast says it will be sunny on Saturday.",
  },
  {
    id: "demo-10",
    sequence: 10,
    at: "00:56",
    sourceLanguage: "en",
    ja: "それなら完璧ですね。",
    en: "That would be perfect.",
  },
  {
    id: "demo-11",
    sequence: 11,
    at: "01:02",
    sourceLanguage: "ja",
    ja: "日焼け止めを忘れないでくださいね。",
    en: "Don't forget to bring sunscreen.",
  },
  {
    id: "demo-12",
    sequence: 12,
    at: "01:08",
    sourceLanguage: "en",
    ja: "もちろんです。飲み物もたくさん持っていきます。",
    en: "Of course. We'll bring plenty of water too.",
  },
  {
    id: "demo-13",
    sequence: 13,
    at: "01:16",
    sourceLanguage: "ja",
    ja: "写真を撮ったら、あとで見せてください。",
    en: "Please show me the photos afterward.",
  },
  {
    id: "demo-14",
    sequence: 14,
    at: "01:22",
    sourceLanguage: "en",
    ja: "いいですよ。たくさん撮ってきます。",
    en: "Sure. I'll take lots of them.",
  },
  {
    id: "demo-15",
    sequence: 15,
    at: "01:28",
    sourceLanguage: "ja",
    ja: "では、楽しい週末を！",
    en: "Have a great weekend, then!",
  },
  {
    id: "demo-16",
    sequence: 16,
    at: "01:31",
    sourceLanguage: "en",
    ja: "ありがとう。また月曜日に！",
    en: "Thanks. See you on Monday!",
  },
];
